app/forms/urls.py
from django.urls import path, include
from app.forms import views


app_name='form'

#
urlpatterns = (
    # urls for MainForm
    path('main-form/', views.FormListView.as_view(), name='main_form_list'),
    path('main-form/create/', views.main_form_create, name='main_form_create'),
    path('main-form/update/<int:pk>/', views.main_form_update, name='main_form_update'),
    path('main-form/delete/<int:pk>/', views.main_form_delete, name='main_form_delete'),
    path('main-form/print/<int:pk>/', views.main_form_print, name='main_form_print'),

    # urls for result
    path('result/', views.ResultListView.as_view(), name='result_list'),
    path('result/create/<int:main_form_id>/', views.result_create, name='result_create'),
    path('result/update/<int:pk>/', views.result_update, name='result_update'),
    path('result/delete/<int:pk>/', views.result_delete, name='result_delete'),
)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from project.views import home, login, signup
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('form/', include('app.forms.urls')),
    url(r'^signup/$', signup, name='signup'),

    path('login/', login, name="login"),
    path('logout/', login, name="logout"),
    path('', login),
]

app/forms/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class MainForm(models.Model):
    name = models.CharField(max_length=30)
    detail = models.CharField(max_length=50, blank=True, null=True, default=None)

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('form:main_form_list')
    
    def get_update_url(self):
        return reverse('form:main_form_update', args=(self.pk,))

    def get_delete_url(self):
        return reverse('form:main_form_delete', args=(self.pk,))
    
    def get_print_url(self):
        return reverse('form:main_form_print', args=(self.pk,))

    def __str__(self):
        return self.name


class Outcome(models.Model):
    name = models.CharField(max_length=50)
    main_form = models.ForeignKey('MainForm', related_name='+', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    name = models.CharField(max_length=50)
    detail = models.CharField(max_length=100, blank=True, null=True)
    score = models.CharField(max_length=50)
    outcome = models.ForeignKey('Outcome', related_name='+', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Result(models.Model):
    main_form = models.ForeignKey('MainForm', related_name='+', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE, null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('form:result_list')
    
    def get_update_url(self):
        return reverse('form:result_update', args=(self.pk,))

    def get_delete_url(self):
        return reverse('form:result_delete', args=(self.pk,))

    def __str__(self):
        return "Result: {}".format(self.pk)


class ResultLine(models.Model):
    result = models.ForeignKey('Result', related_name='+', on_delete=models.CASCADE)
    outcome = models.ForeignKey('Outcome', related_name='+', on_delete=models.CASCADE, blank=True, null=True)
    feedback = models.ForeignKey('Feedback', related_name='+', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        ordering = ('pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def __str__(self):
        return "{}: {}({})".format(self.result.main_form, self.outcome, self.feedback.score)

app/forms/admin.py
from django.contrib import admin
from django import forms
from .models import MainForm, Feedback, Result, Outcome, ResultLine

# Register your models here.
class MainFormAdminForm(forms.ModelForm):
    
    class Meta:
        model = MainForm
        fields = '__all__'


class MainFormAdmin(admin.ModelAdmin):
    form = MainFormAdminForm
    list_display = ['name', 'detail']

admin.site.register(MainForm, MainFormAdmin)



class OutcomeAdminForm(forms.ModelForm):
    
    class Meta:
        model = Outcome
        fields = '__all__'


class OutcomeAdmin(admin.ModelAdmin):
    form = MainFormAdminForm
    list_display = ['name', 'main_form']

admin.site.register(Outcome, OutcomeAdmin)


class FeedbackAdminForm(forms.ModelForm):
    
    class Meta:
        model = Feedback
        fields = '__all__'


class FeedbackAdmin(admin.ModelAdmin):
    form = FeedbackAdminForm
    list_display = ['name', 'detail', 'score', 'outcome']

admin.site.register(Feedback, FeedbackAdmin)


class ResultAdminForm(forms.ModelForm):
    
    class Meta:
        model = Result
        fields = '__all__'


class ResultAdmin(admin.ModelAdmin):
    form = ResultAdminForm
    list_display = ['main_form' , 'user', 'create_at', 'update_at']

admin.site.register(Result, ResultAdmin)


class ResultLineAdminForm(forms.ModelForm):
    
    class Meta:
        model = ResultLine
        fields = '__all__'


class ResultLineAdmin(admin.ModelAdmin):
    form = ResultLineAdminForm
    list_display = ['result', 'outcome', 'feedback']

admin.site.register(ResultLine, ResultLineAdmin)

app/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

app/forms/forms.py
from django import forms
from .models import MainForm, Feedback, Result, Outcome, ResultLine

class MainFormForm(forms.ModelForm):
    class Meta:
        model = MainForm
        fields = ['name', 'detail']


class OutcomeForm(forms.ModelForm):
    class Meta:
        model = Outcome
        fields = ['name', 'main_form']


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'detail', 'score', 'outcome']


class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ['main_form']


class ResultLineForm(forms.ModelForm):
    class Meta:
        model = ResultLine
        fields = ['result', 'outcome', 'feedback']

app/forms/tests.py
from django.test import TestCase

# Create your tests here.

app/forms/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import ListView
from .forms import MainFormForm, ResultForm
from .models import MainForm, Feedback, Result, Outcome, ResultLine
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import datetime

TEMPLATE_PATH = 'app/forms/templates/'

# Create your views here.
class FormListView(ListView):
    models = MainForm
    template_name = TEMPLATE_PATH + 'main_form_list.html'

    def get_queryset(self):
        return MainForm.objects.order_by('-pk')


def main_form_create(request):
    if request.method == 'GET':
        outcome_list = []
        outcome_feedback = {
            'outcome': [Outcome()],
            'feedback_list': [Feedback()],
        }
        outcome_list.append(outcome_feedback)
        context = {
            'outcome_list': outcome_list,
        }
        return render(request, TEMPLATE_PATH + 'main_form_form.html', context)

    elif request.method == 'POST':
        def save_feedback(request, outcome, count):
            count_feedback = int(request.POST.get('count_feedback['+str(count)+']', None))
            for i in range(0, count_feedback):
                try:
                    feedback = Feedback.objects.get(pk=int(request.POST.get('feedback_list['+str(count)+']['+str(i)+'].id', None)))
                except:
                    feedback = Feedback()
                feedback.name = request.POST.get('feedback_list['+str(count)+']['+str(i)+'].name', None)
                feedback.detail = request.POST.get('feedback_list['+str(count)+']['+str(i)+'].detail', None)
                feedback.score = request.POST.get('feedback_list['+str(count)+']['+str(i)+'].score', None)
                feedback.outcome = outcome
                feedback.save()
        
        def save_outcome(request, main_form):
            count_outcome = int(request.POST.get('count_outcome', None))
            for i in range(0, count_outcome):
                try:
                    outcome = Outcome.objects.get(pk=int(request.POST.get('outcome_list['+str(i)+'].id', None)))
                except:
                    outcome = Outcome()
                outcome.name = request.POST.get('outcome_list['+str(i)+'].name', None)
                outcome.main_form = main_form
                outcome.save()
                save_feedback(request, outcome, i)

        form = MainFormForm(request.POST)
        if form.is_valid():
            main_form = form.save(commit=False)
            if request.POST.get("id", "") != '':
                main_form_temp = MainForm.objects.get(pk=int(request.POST.get("id", "")))
                main_form.id = main_form_temp.id
            main_form.save()

            save_outcome(request, main_form)
        else:
            print(form.errors)

        return HttpResponseRedirect(reverse('form:main_form_list'))


def main_form_update(request, pk):
    if request.method == 'GET':
        main_form = MainForm.objects.get(pk=pk)
        outcome_list = []
        for outcome in Outcome.objects.filter(main_form=main_form):
            feedback_list = Feedback.objects.filter(outcome=outcome)
            outcome_feedback = {
                'outcome': outcome,
                'feedback_list': feedback_list,
            }
            outcome_list.append(outcome_feedback)
        context = {
            'main_form': main_form,
            'outcome_list': outcome_list,
        }
        return render(request, TEMPLATE_PATH + 'main_form_form.html', context)


def main_form_delete(request, pk):
    MainForm.objects.filter(pk=pk).delete()
    return HttpResponseRedirect(reverse('form:main_form_list'))


def main_form_print(request, pk):
    if request.method == 'GET':
        main_form = MainForm.objects.get(pk=pk)
        context = {
            'main_form': main_form,
        }
        return render(request, TEMPLATE_PATH + 'main_form_print.html', context)


class ResultListView(ListView):
    models = Result
    template_name = TEMPLATE_PATH + 'result_list.html'

    def get_queryset(self):
        return Result.objects.order_by('-pk')


def result_create(request, main_form_id):
    if request.method == 'GET':
        main_form_list = MainForm.objects.all()
        if main_form_id > 0:
            main_form = MainForm.objects.get(pk=int(main_form_id))
            result_line_list = []
            for outcome in Outcome.objects.filter(main_form=main_form):
                feedback_list = Feedback.objects.filter(outcome=outcome)
                outcome_feedback = {
                    'outcome': outcome,
                    'feedback_list': feedback_list,
                }
                result_line_list.append(outcome_feedback)
        else:
            main_form = None
            result_line_list = [ResultLine()]
        context = {
            'main_form_list': main_form_list,
            'main_form': main_form,
            'main_form_id': main_form_id,
            'result_line_list': result_line_list,
        }
        return render(request, TEMPLATE_PATH + 'result_form.html', context)
    
    elif request.method == 'POST':
        def save_result_line(request, result):
            count_result_line = int(request.POST.get('count_result_line', None))
            for i in range(0, count_result_line):
                try:
                    result_line = ResultLine.objects.get(pk=int(request.POST.get('result_line_list['+str(i)+'].id', None)))
                except:
                    result_line = ResultLine()
                try:
                    outcome = Outcome.objects.get(pk=int(request.POST.get('result_line_list['+str(i)+'].outcome', None)))
                except:
                    outcome = None
                try:
                    feedback = Feedback.objects.get(pk=int(request.POST.get('result_line_list['+str(i)+'].feedback', None)))
                except:
                    feedback = None
                result_line.outcome = outcome
                result_line.feedback = feedback
                result_line.result = result
                result_line.save()

        form = ResultForm(request.POST)
        if form.is_valid():
            result = form.save(commit=False)
            if request.POST.get("id", "") != '':
                result_temp = Result.objects.get(pk=int(request.POST.get("id", "")))
                result.id = result_temp.pk
                result.create_at = result_temp.create_at
                result.update_at = datetime.datetime.now()
            result.user = request.user
            result.save()

            save_result_line(request, result)
        else:
            print(form.errors)

        return HttpResponseRedirect(reverse('form:result_list'))


def result_update(request, pk):
    if request.method == 'GET':
        main_form_list = MainForm.objects.all()
        result = Result.objects.get(pk=pk)
        result_line_list = []
        for result_line in ResultLine.objects.filter(result=result):
            feedback_list = Feedback.objects.filter(outcome=result_line.outcome)
            outcome_feedback = {
                'result_line': result_line,
                'feedback_list': feedback_list,
            }
            result_line_list.append(outcome_feedback)
        main_form_id = result.main_form.pk
        context = {
            'main_form_list': main_form_list,
            'main_form_id': main_form_id,
            'result': result,
            'result_line_list': result_line_list,
        }
        return render(request, TEMPLATE_PATH + 'result_form.html', context)


def result_delete(request, pk):
    Result.objects.filter(pk=pk).delete()
    return HttpResponseRedirect(reverse('form:result_list'))

app/forms/templates/main_form_form.html
{% extends "templates/base_template.html" %}
{% load static crispy_forms_tags %}

{% block title %} Main Form Create{% endblock title %}

{% block content %}
<!-- body -->
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Main Form <small>Create</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>

        <div class="x_content">

          <form data-parsley-validate class="form-horizontal form-label-left"
              action="{% url 'form:main_form_create' %}" method="post">
            {% csrf_token %}

            <div class="form-group">
              <label class="control-label col-sm-2">Title</label>
              <div class="col-sm-4">
                <input type="hidden" name="id" value="{{ main_form.pk }}">
                <input type="text" id="name" name="name" class="form-control"
                    value="{{ main_form.name }}" required>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2">Description</label>
              <div class="col-sm-4">
                <input type="text" id="detail" name="detail" value="{{ main_form.detail }}" class="form-control">
              </div>
            </div>

            <div class="super-clone-container">
              <input type="hidden" id="count_outcome" name="count_outcome"
                  class="form-control number_decimal clone-counter" 
                  value="{{ outcome_list|length|default:1 }}">
              {% for outcome in outcome_list %}
                <div class="form-group clone-container">
                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <label class="control-label col-sm-2 running-label">Outcome {{ forloop.counter }}</label>
                    <div class="col-sm-8">
                      <input type="hidden" name="outcome_list[{{ forloop.counter0 }}].id" value="{{ outcome.outcome.pk }}">
                      <input type="text" name="outcome_list[{{ forloop.counter0 }}].name" class="form-control" 
                          value="{{ outcome.outcome.name|default_if_none:'' }}" required>
                    </div>
  
                    {% if outcome_list|length == forloop.counter %}
                      <div class="col-sm-1">
                        <button type="button" onclick="cloneForm($(this))" class="btn btn-success">
                          <i class="glyphicon glyphicon-plus"></i> Outcome
                        </button>
                      </div>
                    {% endif %}
                  </div>
  
                  <div class="super-clone-container">
                    <input type="hidden" id="count_feedback__{{ forloop.counter }}" 
                        class="form-control number_decimal clone-counter sub-count"
                        name="count_feedback[{{ forloop.counter0 }}]" 
                        value="{{ outcome.feedback_list|length|default:1 }}">
                    {% for feedback in outcome.feedback_list %}
                      <div class="form-group clone-container sub-container">
                        <div class="form-group">
                          <label class="control-label col-sm-3 running-label">Feedback {{ forloop.counter }}</label>
                          <div class="col-sm-4">
                            <input type="hidden" name="feedback_list[{{ forloop.parentloop.counter0 }}][{{ forloop.counter0 }}].id" 
                                value="{{ feedback.pk }}">
                            <input type="text" name="feedback_list[{{ forloop.parentloop.counter0 }}][{{ forloop.counter0 }}].name" 
                                value="{{ feedback.name|default_if_none:'' }}" class="form-control" required>
                          </div>
                        </div>
    
                        <div class="form-group">
                          <label class="control-label col-sm-3 running-label">Description {{ forloop.counter }}</label>
                          <div class="col-sm-4">
                            <input type="text" name="feedback_list[{{ forloop.parentloop.counter0 }}][{{ forloop.counter0 }}].detail" 
                                value="{{ feedback.detail|default_if_none:'' }}" class="form-control">
                          </div>
                          
                          <label class="control-label col-sm-1 running-label">Score {{ forloop.counter }}</label>
                          <div class="col-sm-2">
                            <input type="text" name="feedback_list[{{ forloop.parentloop.counter0 }}][{{ forloop.counter0 }}].score"
                                class="form-control" value="{{ feedback.score|default_if_none:'' }}" required>
                          </div>
                          {% if outcome.feedback_list|length == forloop.counter %}
                            <div class="col-sm-2">
                              <button type="button" onclick="cloneForm($(this))" class="btn btn-info">
                                  <i class="glyphicon glyphicon-plus"></i> Feedback
                              </button>
                            </div>
                          {% endif %}
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}
            </div>

            <div class="ln_solid"></div>

            <div class="form-group">
              <div class="col-md-offset-5">
                <button class="btn btn-primary" type="submit">Submit</button>
                <a class="btn btn-danger" href="{% url 'form:main_form_list' %}">Cancel</a>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
<!-- end body -->
{% endblock %}

app/forms/templates/main_form_list.html
{% extends "templates/base_template.html" %}

{% block title %} Main Form Lists{% endblock title %}

{% block content %}
<div class="right_col" role="main">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

        <div class="x_title">
              <h2>Main Form <small>Lists</small></h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
         </div>

          {% if user.is_superuser %}
         <div class="x_title">
            <a class="btn btn-app" href="{% url 'form:main_form_create' %}"><i class="fa fa-plus"></i>Add</a>
            {% comment %} <a class="btn btn-app" href="{% url 'form:result_list' %}"><i class="fa fa-list"></i>Result</a> {% endcomment %}
         </div>
         {% endif %}

        <div class="x_content">
              <table class="table table-bordered basicdata-table table-striped">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Action</th>
                   </tr>
                   </thead>
                  <tbody>
                  
                  {% for form in object_list %}
                    <tr>
                        <td>{{ form.name }}</td>
                        <td>{{ form.detail }}</td>
                       <td>
                          <a href="{{form.get_update_url}}"><button class="btn btn-info" type="button">Edit</button></a>
                          {% comment %} <a href="{{ form.get_print_url }}" class="btn btn-warning btn-sm">Preview</a> {% endcomment %}
                          <a href="{{form.get_delete_url}}"><button class="btn btn-danger confirm-delete" type="button">Delete</button></a>
                        </td>
                    </tr>
                    {% endfor %} 

                  </tbody>
            </table>
          </div>
          
        </div>
      </div>
  </div>
</div>
{% endblock content%}

app/forms/templates/result_form.html
{% extends "templates/base_template.html" %}
{% load static crispy_forms_tags %}

{% block title %} Add Result{% endblock title %}

{% block content %}
<!-- body -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Add Result</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <form id="result_form" data-parsley-validate class="form-horizontal form-label-left" 
                            action="{% url 'form:result_create' main_form_id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2">Title</label>
                            <div class="col-sm-4">
                                <input type="hidden" name="id" value="{{ result.pk }}">
                                <select required class="select2 form-control" name="main_form"
                                        onchange="changeMainForm(this.value)">
                                    <option value="" selected="selected">--Title--</option>
                                    {% for main_form in main_form_list %}
                                    <option value="{{ main_form.pk }}" 
                                            {% if result is None and main_form.pk == main_form_id %}
                                                selected="selected"
                                            {% elif result is not None and main_form.pk == result.main_form.pk %}
                                                selected="selected"
                                            {% endif %}> 
                                        {{ main_form.name }}
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2">Description</label>
                            <div class="col-sm-4">
                                <input readonly class="form-control" 
                                        value="{% if result is None %}{{ main_form.detail }}{% else %}{{ result.main_form.detail }}{% endif %}">
                            </div>
                        </div>

                        <input type="hidden" name="count_result_line" value="{{ result_line_list|length|default_if_none:1 }}">
                        {% for result_line in result_line_list %}
                            <div class="form-group">
                                <label class="control-label col-sm-2">Outcome {{ forloop.counter }}</label>
                                <div class="col-sm-4">
                                    <input type="hidden" name="result_line_list[{{ forloop.counter0 }}].id" value="{{ result_line.result_line.pk }}">
                                    <input type="hidden" name="result_line_list[{{ forloop.counter0 }}].outcome" 
                                            value="{% if result is None %}{{ result_line.outcome.pk }}{% else %}{{ result_line.result_line.outcome.pk }}{% endif %}">
                                    <input required readonly class="form-control" 
                                            value="{% if result is None %}{{ result_line.outcome.name }}{% else %}{{ result_line.result_line.outcome.name }}{% endif %}">
                                </div>

                                <div class="col-sm-3">
                                    <select class="select2 form-control" name="result_line_list[{{ forloop.counter0 }}].feedback" required>
                                        <option value="" selected="selected">--Score--</option>
                                        {% for feedback in result_line.feedback_list %}
                                            <option value="{{ feedback.pk }}" 
                                                    {% if feedback.pk == result_line.result_line.feedback.pk %} selected="selected" {% endif %}>
                                                {{ feedback.score }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        {% endfor %}

                        <div class="form-group">
                            <div class="col-md-offset-5">
                                <button class="btn btn-primary" type="submit">Submit</button>
                                <a class="btn btn-danger" href="{% url 'form:result_list' %}">Cancel</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- end body -->

{% endblock %}

{% block javascripts %}
    {{ block.super}}
    <script>

        function changeMainForm(main_form_id) {
            if(main_form_id != ""){
                var form = document.getElementById("result_form");
                form.action = "{% url 'form:result_create' 0 %}".replace(/0/, main_form_id);
                form.method = "get";
                form.submit();
            }
        }

    </script>
{% endblock javascripts %}

app/forms/templates/result_list.html
{% extends "templates/base_template.html" %}

{% block title %} Result Lists {% endblock title %}

{% block content %}
<div class="right_col" role="main">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

        <div class="x_title">
          <h2>Result <small>Lists</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>

        <div class="x_title">
          <a class="btn btn-app" href="{% url 'form:result_create' 0 %}"><i class="fa fa-plus"></i>Add</a>
        </div>

        <div class="x_content">
              <table class="table table-bordered basicdata-table table-striped">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>score</th>
                    <th>feedback</th>
                    <th>user</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for result in object_list %}
                    <tr>
                      <td>{{ result.main_form.name }}</td>
                      <td>{{ result.main_form.detail }}</td>
                      <td>{{ result.feedback.score }}</td>
                      <td>{{ result.feedback.detail }}</td>
                      <td>{{ result.user }}</td>
                      <td>
                        <a href="{{result.get_update_url}}"><button class="btn btn-info" type="button">Edit</button></a>
                        <a href="{{result.get_delete_url}}"><button class="btn btn-danger confirm-delete" type="button">Delete</button></a>
                      </td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>
          </div>
          
        </div>
      </div>
  </div>
</div>
{% endblock content%}