app/forms/urls.py
from django.urls import path, include
from app.forms import views


app_name='form'

#
urlpatterns = (
    # urls for MainForm
    path('main-form/', views.FormListView.as_view(), name='main_form_list'),
    path('main-form/create/', views.main_form_create, name='main_form_create'),
    path('main-form/update/<int:pk>/', views.main_form_update, name='main_form_update'),
    path('main-form/delete/<int:pk>/', views.main_form_delete, name='main_form_delete'),
    path('main-form/print/<int:pk>/', views.main_form_print, name='main_form_print'),

    # urls for result
    path('result/', views.ResultListView.as_view(), name='result_list'),
    path('result/create/<int:main_form_id>/', views.result_create, name='result_create'),
    path('result/update/<int:pk>/', views.result_update, name='result_update'),
    path('result/delete/<int:pk>/', views.result_delete, name='result_delete'),
)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from project.views import home, login, signup
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('form/', include('app.forms.urls')),
    url(r'^signup/$', signup, name='signup'),

    path('login/', login, name="login"),
    path('logout/', login, name="logout"),
    path('', login),
]

templates/base_template.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>CES | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href={% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %} rel="stylesheet">
        <!-- Font Awesome -->
        <link href={% static 'vendors/font-awesome/css/font-awesome.min.css' %} rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href={% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %} rel="stylesheet">
        <!-- iCheck -->
        <link href={% static 'vendors/iCheck/skins/flat/green.css' %} rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href={% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %} rel="stylesheet">
        <!-- Datepicker -->
        <!-- <link href={% static 'vendors/datepicker/bootstrap-datepicker3.css' %} rel="stylesheet"/> -->
        <!-- Select2 -->
        <link href="{% static 'vendors/select2/dist/css/select2.min.css' %}" rel="stylesheet" />
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="{% static 'build/css/custom.css' %}" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md menu_fixed{% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "templates/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "templates/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

         
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src={% static 'vendors/jquery/dist/jquery.min.js' %}></script>
        <!-- Bootstrap -->
        <script src={% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}></script>
        <!-- bootstrap-progressbar -->
        <script src={% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}></script>
        <!-- iCheck -->
        <script src={% static 'vendors/iCheck/icheck.min.js' %}></script>
        <!-- bootstrap-daterangepicker -->
        <script src={% static 'vendors/moment/min/moment.min.js' %}></script>
        <script src={% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}></script>
        <!-- jQuery Tags Input -->
        <script src={% static 'vendors/jquery.tagsinput/src/jquery.tagsinput.js' %}></script>
        <!-- Select2 -->
        <script src={% static 'vendors/select2/dist/js/select2.full.min.js' %}></script>
        <!-- Parsley -->
        <script src={% static 'vendors/parsleyjs/dist/parsley.min.js' %}></script>
        <!-- Autosize -->
        <script src={% static 'vendors/autosize/dist/autosize.min.js' %}></script>
        <!-- jQuery autocomplete -->
        <script src={% static 'vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js' %}></script>
        <!-- datepicker -->
        <!--  <script src={% static 'vendors/datepicker/bootstrap-datepicker.min.js' %}></script> -->
        <!-- Inputmask -->
        <script src={% static 'vendors/Inputmask-4.x/dist/jquery.inputmask.bundle.js' %}></script>
        <!-- dataTable -->
        <script src={% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}></script>
        <script src={% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}></script>
        <script src={% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src={% static 'build/js/custom.js' %}></script>

      <script type="text/javascript">
          $(document).ready(function() {
            $('.select2').select2();
          });
      </script>
    {% endblock body %}
  </body>
</html>

templates/home.html
{% extends "base_template.html" %}
{% load static%}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/index.html
{% extends "templates/base_template.html" %}

{% block title %} Home {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

templates/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'home' %}" class="site_title"><i class="fa fa-file"></i> <span>CES</span></a>
  </div>

  <div class="clearfix"></div>

  <br />
  
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
        <li><a href="{% url 'form:main_form_list' %}" >Main Form List</a> </li>
        <li><a href="{% url 'form:result_list' %}" >Result List</a> </li>
      </ul>
    </div>
  </div>
</div>

templates/signup.html
{% load static%}
{% load crispy_forms_tags %}
<!DOCTYPE html>



<html lang="en-us">

<head>
  <title>Sign Up</title>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />

  <link rel="stylesheet" type="text/css" href="/static/jet/css/vendor.css?v=1.0.8" />
  <link rel="stylesheet" type="text/css" href="/static/jet/css/icons/style.css?v=1.0.8" />
  <link rel="stylesheet" type="text/css" href="/static/jet/css/themes/default/base.css?v=1.0.8"
    class="base-stylesheet" />
  <link rel="stylesheet" type="text/css" href="/static/jet/css/themes/default/select2.theme.css?v=1.0.8"
    class="select2-stylesheet" />
  <link rel="stylesheet" type="text/css" href="/static/jet/css/themes/default/jquery-ui.theme.css?v=1.0.8"
    class="jquery-ui-stylesheet" />

  <link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">

</head>

<body class="menu-pinned  login">

  <!-- Container -->
  <div id="container">



    <!-- Content -->
    <div id="content" class="colM">
      <div id="content-main">
        {% block content %}
          <div class="form-row" style="text-align:center">
            <h2>Sign up</h2>
          </div>
        <form method="post">
          {% csrf_token %}
      
        {% crispy form %}
        <div class="submit-row">
          <button type="submit" class="button default">Sign up</button>
          <a href="{% url 'login' %}"><button class="button" type="button">Back</button></a>
        </div>
        </form>
        {% endblock %}
      </div>
      <br class="clear" />
    </div>
  </div>

</body>

</html>

templates/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="/static/images/img1.jpg" alt="">{% firstof user.get_short_name user.get_username %}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          <li><a href="/logout/"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
        </ul>
      </li>
    </ul>
  </nav>
</div>